### ISSUE TITLE
Script isn't disliking every song

### ISSUE THREAD

**Issue by muhdiboy** [grimm26/ytm_dislike_artist#1]
Hi,

the script is running through and listing every song of the artist but isn't disliking every one of them. I tested this with an artist with only one album and it just disliked 5 out of 10 songs. I chose "Ronin Rey" for this test (just tried to find someone with just a few songs). 
![image](https://user-images.githubusercontent.com/34396536/138623732-08e54be2-a90d-4727-a468-ba0717b0e606.png)

Running the script multiple times didn't help.
Is there some sort of protection against mass dislikes or something?

**Comment by grimm26** [comment]
https://github.com/grimm26/ytm_dislike_artist/pull/4 should fix this.
@muhdiboy let me know

**Comment by muhdiboy** [comment]
Hi,

thank you for the adjustments. The script did improve by some amount. I do have to run the script multiple times and then dislike the remaining tracks manually. I think this is still an improvement overall. If you can improve this any further to a point where it dislikes every single track this script will become perfect.

Much appreciated anyways. Hit me up for further tests.

**Comment by grimm26** [comment]
all I did was make it wait a tenth of a second between rating tracks. That seemed enough, but you can kick it up to a second and that may help (but will be slow). When I have a minute I'll add an option to specify the sleep time.

**Comment by grimm26** [comment]
I increased the sleep between dislikes to a full second. That makes it always work for me.
